### ISSUE TITLE
invalidateRendering() leaking <defs> nodes/memory

### ISSUE THREAD

**Issue by jfgilliam** [ibm-js/dgauges#7]
Here is a JSFiddle, http://jsfiddle.net/cQ7VR/2/, that can be used to illustrate the problem. I modified the fiddle used in my previous issue and added a aspect.before to check the value clicked. Normally, I would do something based on the value, such as change the colors of the gauge, etc. I'm my simple example, I just call invalidateRendering() if the value is over 50. So, if you inspect the DOM, every time you click a value above 50, it adds more nodes to the defs. I have a real-world gauge being fed values and it runs out of memory real soon. I would expect the invalidateRendering() would replace the nodes, not keep adding to them.

**Comment by dmandrioli** [comment]
Thank you for reporting, this bug is related to https://bugs.dojotoolkit.org/ticket/14037
I've created the issue #8.

Calling invalidateRendering on the gauge triggers a full redraw of the gauge, it's probably not what you want. The good practice is to invalidate only affected gauge elements.
You're currently subclassing a predefined gauge, it's not a bad idea but if you're building advanced gauges, I strongly encourage you to build a custom gauge. This means subclassing CircularGauge instead of a predefined gauge. You have custom gauges examples in tests/gauges directory.

If you want to draw another background on value change, you will have to manage the memory with the GFX destroy() method, see http://dojotoolkit.org/reference-guide/1.9/dojox/gfx.html
